language: php

php:
  - 5.3

before_script:
  - mysql -e 'CREATE DATABASE lightning_test;'
  - composer --version
  - composer install --dev

script:
#  - bin/phpunit -c app/ --coverage-text
  - bin/phpcs --standard=PSR2 -n src/
