language: php

php:
  - 5.3
  - 5.4

before_script:
  - mysql -e 'CREATE DATABASE lightning_test;'
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install --dev

script:
  - bin/phpunit -c app/ --coverage-text
  - bin/phpcs --standard=PSR2 -n src/

notifications:
  webhooks:
    urls:
      - http://lightning.farnsworth.ch/deploy.php
    on_success: always
    on_failure: never
