language: php

php:
  - 5.3

before_script:
  - mysql -e 'CREATE DATABASE lightning_test;'
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install --dev

script:
  - vendor/bin/phpunit -c app/ --coverage-clover "clover"
  - vendor/bin/phpcs --standard=PSR2 -n src/

notifications:
  webhooks:
    urls:
      - http://lightning.farnsworth.ch/deploy.php
    on_success: always
    on_failure: never

after_success:
  - curl -sL https://bit.ly/artifact-uploader | php
