imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

lightning_api:
    urbanairship_key: ABC123
    urbanairship_secret: DEF987
    appstore_verify_url: http://example.com/verifyReceipt

doctrine:
    dbal:
        dbname:   %database_name_test%

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
