parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: lightning
    database_name_test: lightning_test
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 579f85a6a7cb52df9101107ba82714f509
    database_path: null
